artifacts:
  files:
  - helloworld/transformed.yaml
  type: zip
env:
  secrets-manager:
    ACCESS_KEY: "AWSCredentials:ACCESS_KEY"
    SECRET_KEY: "AWSCredentials:SECRET_KEY"
phases:
  build:
    commands:
    - jq --arg ACCESS_KEY "$ACCESS_KEY" --arg SECRET_KEY "$SECRET_KEY" '.stages.dev.environment_variables.ACCESS_KEY=$ACCESS_KEY | .stages.dev.environment_variables.SECRET_KEY=$SECRET_KEY' .chalice/config.json > .chalice/config..tmp && mv .chalice/config.tmp .chalice/config.json
    - chalice package /tmp/packaged
    - aws cloudformation package --template-file /tmp/packaged/sam.json --s3-bucket
      ${APP_S3_BUCKET} --output-template-file transformed.yaml
  install:
    commands:
    - cd helloworld
    - pip install 'chalice>=1.22.0,<1.23.0'
    - pip install -r requirements.txt
    runtime-versions:
      python: '3.8'
version: '0.2'
